steps:
  - block: 'Trigger a basic build'
    key: 'trigger-basic-build'

  - label: 'Upload the basic test pipeline'
    key: 'upload-basic-build'
    agents:
      queue: macos
    timeout_in_minutes: 2
    depends_on: 'trigger-basic-build'
    command: >
      buildkite-agent pipeline upload .buildkite/pipeline.basic.yml
