steps:
  - block: 'Trigger a full build'
    key: 'trigger-full-build'

  - label: 'Upload the full test pipeline'
    depends_on: 'trigger-full-build'
    command: >
#      buildkite-agent pipeline upload .buildkite/pipeline.android.full.yml &&
#      buildkite-agent pipeline upload .buildkite/pipeline.ios.full.yml &&
#      buildkite-agent pipeline upload .buildkite/pipeline.windows.full.yml &&
#      buildkite-agent pipeline upload .buildkite/pipeline.macos.full.yml &&
      buildkite-agent pipeline upload .buildkite/pipeline.linux.full.yml &&
#      echo "Waiting on https://smartbear.atlassian.net/browse/PLAT-12563 buildkite-agent pipeline upload .buildkite/pipeline.linux.full.yml" &&
#      buildkite-agent pipeline upload .buildkite/pipeline.webgl.full.yml
