aliases:
  - &2021 "2021.3.36f1"

agents:
  queue: macos-14

steps:
  - label: Build released notifier artifact
    key: "build_unitypackage"
    timeout_in_minutes: 30
    env:
      UNITY_VERSION: *2021
    commands:
      - bundle install
      - bundle exec rake plugin:export
    artifact_paths:
      - Bugsnag.unitypackage
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: 'Append Unity 6000 Pipeline'
    timeout_in_minutes: 2
    commands:
        - buildkite-agent pipeline upload .buildkite/unity.6000.yml
