steps:

  #
  # Conditionally trigger basic pipeline
  #
  - label: "Conditionally trigger basic pipeline"
    agents:
      queue: macos
    timeout_in_minutes: 2
    command: sh -c .buildkite/pipeline_trigger_basic.sh
