aliases:
  - &2020 "2020.3.48f1"
  - &2021 "2021.3.36f1"
  - &2022 "2022.3.22f1"
  - &2023 "2023.2.19f1"

# Waiting on https://smartbear.atlassian.net/browse/PLAT-12563
agents:
  queue: macos-14

timeout_in_minutes: 60

steps:
  #
  # Build Linux test fixtures
  #

# Skipped - PLAT-12628
#  - label: Build Unity 2020 Linux test fixture
#    timeout_in_minutes: 30
#    key: "linux-2020-fixture"
#    depends_on: "build-artifacts"
#    env:
#      UNITY_VERSION: *2020
#    plugins:
#      artifacts#v1.9.0:
#        download:
#          - Bugsnag.unitypackage
#        upload:
#          - unity.log
#          - features/fixtures/maze_runner/build/linux-release-2020.zip
#    commands:
#      - scripts/ci-build-linux-fixture.sh release
#    retry:
#      automatic:
#        - exit_status: "*"
#          limit: 1

  - label: Build Unity 2021 linux test fixture
    timeout_in_minutes: 30
    key: "linux-2021-fixture"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: *2021
    commands:
      - scripts/ci-build-linux-fixture.sh release
    plugins:
      artifacts#v1.9.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - unity.log
          - unity_import.log
          - features/fixtures/maze_runner/build/linux-release-2021.zip
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

# Skipped - PLAT-12629
#  - label: Build Unity 2021 linux DEV test fixture
#    timeout_in_minutes: 30
#    key: "linux-2021-dev-fixture"
#    depends_on: "build-artifacts"
#    env:
#      UNITY_VERSION: *2021
#    commands:
#      - scripts/ci-build-linux-fixture.sh dev
#    plugins:
#      artifacts#v1.9.0:
#        download:
#          - Bugsnag.unitypackage
#        upload:
#          - unity.log
#          - unity_import.log
#          - features/fixtures/maze_runner/build/linux-dev-2021.zip
#    retry:
#      automatic:
#        - exit_status: "*"
#          limit: 1

  - label: Build Unity 2022 linux test fixture
    timeout_in_minutes: 30
    key: "linux-2022-fixture"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: *2022
    commands:
      - scripts/ci-build-linux-fixture.sh release
    plugins:
      artifacts#v1.9.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - unity.log
          - unity_import.log
          - features/fixtures/maze_runner/build/linux-release-2022.zip
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: Build Unity 2023 linux test fixture
    timeout_in_minutes: 30
    key: "linux-2023-fixture"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: *2023
    commands:
      - scripts/ci-build-linux-fixture.sh release
    plugins:
      artifacts#v1.9.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - unity.log
          - unity_import.log
          - features/fixtures/maze_runner/build/linux-release-2023.zip
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Run linux e2e tests
  #

# Skipped - PLAT-12628
#  - label: Run linux e2e tests for Unity 2020
#    timeout_in_minutes: 30
#    depends_on: "linux-2020-fixture"
#    env:
#      UNITY_VERSION: *2020
#    agents:
#        queue: "opensource-ubuntu-1804-unity"
#    plugins:
#      artifacts#v1.9.0:
#        download:
#          - features/fixtures/maze_runner/build/linux-release-2020.zip
#        upload:
#          - maze_output/**/*
#          - maze_output/metrics.csv
#    command:
#      - scripts/ci-run-linux-tests.sh release

  - label: Run linux e2e tests for Unity 2021
    timeout_in_minutes: 30
    depends_on: "linux-2021-fixture"
    env:
      UNITY_VERSION: *2021
    agents:
      queue: "opensource-ubuntu-1804-unity"
    plugins:
      artifacts#v1.9.0:
        download:
          - features/fixtures/maze_runner/build/linux-release-2021.zip
        upload:
          - maze_output/**/*
          - maze_output/metrics.csv
    commands:
      - scripts/ci-run-linux-tests.sh release

  - label: Run linux e2e DEV tests for Unity 2021
    timeout_in_minutes: 30
    depends_on: "linux-2021-dev-fixture"
    env:
      UNITY_VERSION: *2021
    agents:
      queue: "opensource-ubuntu-1804-unity"
    plugins:
      artifacts#v1.9.0:
        download:
          - features/fixtures/maze_runner/build/linux-dev-2021.zip
        upload:
          - maze_output/**/*
          - maze_output/metrics.csv
    commands:
      - scripts/ci-run-linux-tests.sh dev

# Skipped - PLAT-12629
#  - label: Run linux e2e tests for Unity 2022
#    timeout_in_minutes: 30
#    depends_on: "linux-2022-fixture"
#    env:
#      UNITY_VERSION: *2022
#    agents:
#      queue: "opensource-ubuntu-1804-unity"
#    plugins:
#      artifacts#v1.9.0:
#        download:
#          - features/fixtures/maze_runner/build/linux-release-2022.zip
#        upload:
#          - maze_output/**/*
#          - maze_output/metrics.csv
#    commands:
#      - scripts/ci-run-linux-tests.sh release

  - label: Run linux e2e tests for Unity 2023
    timeout_in_minutes: 30
    depends_on: "linux-2023-fixture"
    env:
      UNITY_VERSION: *2023
    agents:
      queue: "opensource-ubuntu-1804-unity"
    plugins:
      artifacts#v1.9.0:
        download:
          - features/fixtures/maze_runner/build/linux-release-2023.zip
        upload:
          - maze_output/**/*
          - maze_output/metrics.csv
    commands:
      - scripts/ci-run-linux-tests.sh release
