steps:
  #
  # Build notifier.  We run tests for all Unity versions with the 2017 artifacts, as that is what we ship.
  #
  - label: Build notifier artifacts
    key: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2017.4.40f1"
    commands:
      - bundle install
      - bundle exec rake plugin:export
    artifact_paths:
      - Bugsnag.unitypackage
      - Bugsnag-with-android-64bit.unitypackage
    concurrency: 2
    concurrency_group: 'unity-license'

  #
  # Build desktop test fixtures
  #
  - label: Build Unity 2017 MacOS test fixture
    key: 'cocoa-2017-fixture'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2017.4.40f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
    commands:
      - cd test/desktop
      - ./features/scripts/build_maze_runner.sh
    artifact_paths:
      - test/desktop/features/fixtures/Mazerunner-2017.4.40f1.app.zip
    concurrency: 2
    concurrency_group: 'unity-license'

  - label: Build Unity 2018 MacOS test fixture
    key: 'cocoa-2018-fixture'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2018.4.34f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
    commands:
      - cd test/desktop
      - ./features/scripts/build_maze_runner.sh
    artifact_paths:
      - test/desktop/features/fixtures/Mazerunner-2018.4.34f1.app.zip
    concurrency: 2
    concurrency_group: 'unity-license'

  #
  # Run desktop tests
  #
  - label: Run MacOS e2e tests for Unity 2017.4.40f1
    depends_on: 'cocoa-2017-fixture'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-10.15
    env:
      UNITY_VERSION: "2017.4.40f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - test/desktop/features/fixtures/Mazerunner-2017.4.40f1.app.zip
        upload:
          - test/desktop/maze_output/*
          - test/desktop/Mazerunner.log
    commands:
      - cd test/desktop
      - bundle install
      - bundle exec maze-runner --app=Mazerunner

  - label: Run MacOS e2e tests for Unity 2018.4.34f1
    depends_on: 'cocoa-2018-fixture'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-10.15
    env:
      UNITY_VERSION: "2018.4.34f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - test/desktop/features/fixtures/Mazerunner-2018.4.34f1.app.zip
        upload:
          - test/desktop/maze_output/*
          - test/desktop/Mazerunner.log
    commands:
      - cd test/desktop
      - bundle install
      - bundle exec maze-runner --app=Mazerunner

  #
  # Build Android test fixtures
  #
  - label: ':android: Build Android test fixture for Unity 2017'
    key: 'build-android-fixture-2017'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2017.4.40f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
        upload:
          - test/mobile/features/fixtures/maze_runner/mazerunner_2017.4.40f1.apk
          - test/mobile/features/fixtures/unity.log
    commands:
      - rake test:android:build
    concurrency: 2
    concurrency_group: 'unity-license'

  - label: ':android: Build Android test fixture for Unity 2018'
    key: 'build-android-fixture-2018'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2018.4.34f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
        upload:
          - test/mobile/features/fixtures/maze_runner/mazerunner_2018.4.34f1.apk
          - test/mobile/features/fixtures/unity.log
    commands:
      - rake test:android:build
    concurrency: 2
    concurrency_group: 'unity-license'

  - label: ':android: Build Android test fixture for Unity 2019'
    skip: Pending PLAT-6447
    key: 'build-android-fixture-2019'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2019.4.25f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
        upload:
          - test/mobile/features/fixtures/maze_runner/mazerunner_2019.4.25f1.apk
    commands:
      - rake test:android:build
    concurrency: 2
    concurrency_group: 'unity-license'

  #
  # Run Android tests
  #
  - label: ':android: Run Android e2e tests for Unity 2017'
    depends_on: 'build-android-fixture-2017'
    timeout_in_minutes: 30
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download:
          - "test/mobile/features/fixtures/maze_runner/mazerunner_2017.4.40f1.apk"
      docker-compose#v3.3.0:
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2017.4.40f1.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: browserstack-app

  - label: ':android: Run Android e2e tests for Unity 2018'
    depends_on: 'build-android-fixture-2018'
    timeout_in_minutes: 30
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download:
          - "test/mobile/features/fixtures/maze_runner/mazerunner_2018.4.34f1.apk"
      docker-compose#v3.3.0:
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2018.4.34f1.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: browserstack-app

  - label: ':android: Run Android e2e tests for Unity 2019'
    skip: Pending PLAT-6447
    depends_on: 'build-android-fixture-2019'
    timeout_in_minutes: 30
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download:
          - "test/mobile/features/fixtures/maze_runner/mazerunner_2019.4.25f1.apk"
      docker-compose#v3.3.0:
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2019.4.25f1.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: browserstack-app

  #
  # Build iOS test fixtures
  #
  - label: ':ios: Generate test fixture Xcode project for Unity 2017'
    key: 'generate-fixture-project-2017'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2017.4.40f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
        upload:
          - test/mobile/features/fixtures/maze_runner/mazerunner_2017.4.40f1.ipa
          - test/mobile/features/fixtures/unity.log
          - project_2017.tgz
    commands:
      - rake test:ios:generate_xcode
      - tar -zvcf project_2017.tgz  test/mobile/features/fixtures/maze_runner/mazerunner_xcode
    concurrency: 2
    concurrency_group: 'unity-license'

  - label: ':ios: Build iOS test fixture for Unity 2017'
    key: 'build-ios-fixture-2017'
    depends_on: 'generate-fixture-project-2017'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-10.15
    env:
      UNITY_VERSION: "2017.4.40f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
          - project_2017.tgz
        upload:
          - test/mobile/features/fixtures/maze_runner/mazerunner_2017.4.40f1.ipa
          - test/mobile/features/fixtures/unity.log
    commands:
      - tar -zxf project_2017.tgz test/mobile/features/fixtures/maze_runner
      - rake test:ios:build_xcode

  - label: ':ios: Generate test fixture Xcode project for Unity 2018'
    key: 'generate-fixture-project-2018'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2018.4.34f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
        upload:
          - test/mobile/features/fixtures/maze_runner/mazerunner_2018.4.34f1.ipa
          - test/mobile/features/fixtures/unity.log
          - project_2018.tgz
    commands:
      - rake test:ios:generate_xcode
      - tar -zvcf project_2018.tgz  test/mobile/features/fixtures/maze_runner/mazerunner_xcode
    concurrency: 2
    concurrency_group: 'unity-license'

  - label: ':ios: Build iOS test fixture for Unity 2018'
    key: 'build-ios-fixture-2018'
    depends_on: 'generate-fixture-project-2018'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-10.15
    env:
      UNITY_VERSION: "2018.4.34f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
          - project_2018.tgz
        upload:
          - test/mobile/features/fixtures/maze_runner/mazerunner_2018.4.34f1.ipa
          - test/mobile/features/fixtures/unity.log
    commands:
      - tar -zxf project_2018.tgz test/mobile/features/fixtures/maze_runner
      - rake test:ios:build_xcode

  - label: ':ios: Generate test fixture Xcode project for Unity 2019'
    skip: Pending PLAT-6447
    key: 'generate-fixture-project-2019'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2019.4.25f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
        upload:
          - test/mobile/features/fixtures/maze_runner/mazerunner_2019.4.25f1.ipa
          - test/mobile/features/fixtures/unity.log
          - project_2019.tgz
    commands:
      - rake test:ios:generate_xcode
      - tar -zvcf project_2019.tgz test/mobile/features/fixtures/maze_runner/mazerunner_xcode
    concurrency: 2
    concurrency_group: 'unity-license'

  - label: ':ios: Build iOS test fixture for Unity 2019'
    skip: Pending PLAT-6447
    key: 'build-ios-fixture-2019'
    depends_on: 'generate-fixture-project-2019'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-10.15
    env:
      UNITY_VERSION: "2019.4.25f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
          - project_2019.tgz
        upload:
          - test/mobile/features/fixtures/maze_runner/mazerunner_2019.4.25f1.ipa
          - test/mobile/features/fixtures/unity.log
    commands:
      - tar -zxf project_2019.tgz test/mobile/features/fixtures/maze_runner
      - rake test:ios:build_xcode
