aliases:
  - &2020 "2020.3.48f1"
  - &2021 "2021.3.36f1"
  - &2022 "2022.3.22f1"
  - &2023 "2023.2.19f1"

agents:
  queue: macos-14

steps:
  #
  # Build Android test fixtures
  #
  - label: ":android: Build Android test fixture for Unity 2020"
    timeout_in_minutes: 30
    key: "build-android-fixture-2020"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: *2020
    plugins:
      artifacts#v1.9.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2020.apk
          - features/fixtures/build_android_apk.log
    commands:
      - bundle install
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ":android: Build Android DEV test fixture for Unity 2021"
    timeout_in_minutes: 30
    key: "build-android-dev-fixture-2021"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: *2021
    plugins:
      artifacts#v1.9.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_dev_2021.apk
          - features/fixtures/build_android_apk.log
    commands:
      - bundle install
      - rake test:android:build_dev
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ":android: Build Android test fixture for Unity 2022"
    timeout_in_minutes: 30
    key: "build-android-fixture-2022"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: *2022
    plugins:
      artifacts#v1.9.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2022.apk
          - features/fixtures/build_android_apk.log
    commands:
      - bundle install
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ":android: Build Android test fixture for Unity 2023"
    timeout_in_minutes: 30
    key: "build-android-fixture-2023"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: *2023
    plugins:
      artifacts#v1.9.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2023.apk
          - features/fixtures/build_android_apk.log
    commands:
      - bundle install
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  # - label: ':android: Build Android EDM test fixture for Unity 2020'
  #   timeout_in_minutes: 30
  #   key: 'build-edm-fixture-2020'
  #   depends_on: 'build-artifacts'
  #   env:
  #     UNITY_VERSION: *2020
  #   plugins:
  #     artifacts#v1.9.0:
  #       download:
  #         - Bugsnag.unitypackage
  #       upload:
  #         - features/fixtures/EDM_Fixture/edm_2020.apk
  #         - features/scripts/buildEdmFixture.log
  #         - features/scripts/edmImport.log
  #         - features/scripts/enableEdm.log
  #   commands:
  #     - rake test:edm:build
  #   retry:
  #     automatic:
  #       - exit_status: "*"
  #         limit: 1

  #
  # Run Android tests
  #
  - label: ":bitbar: :android: Run Android e2e tests for Unity 2020"
    timeout_in_minutes: 60
    depends_on: "build-android-fixture-2020"
    agents:
      queue: opensource
    env:
      UNITY_VERSION: *2020
    plugins:
      artifacts#v1.9.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2020.apk"
        upload:
          - "maze_output/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner-bitbar
        run: maze-runner-bitbar
        service-ports: true
        command:
          - "features/csharp"
          - "features/android"
          - "--app=features/fixtures/maze_runner/mazerunner_2020.apk"
          - "--farm=bb"
          - "--appium-version=1.22"
          - "--device=ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: "bitbar"
    concurrency_method: eager

  - label: ":bitbar: :android: Run Android DEV e2e tests for Unity 2021"
    timeout_in_minutes: 60
    depends_on: "build-android-dev-fixture-2021"
    agents:
      queue: opensource
    env:
      UNITY_VERSION: *2021
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_dev_2021.apk"
        upload:
          - "maze_output/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner-bitbar
        run: maze-runner-bitbar
        service-ports: true
        command:
          - "features/csharp"
          - "features/android"
          - "--app=features/fixtures/maze_runner/mazerunner_dev_2021.apk"
          - "--farm=bb"
          - "--appium-version=1.22"
          - "--device=ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
    concurrency: 25
    concurrency_group: "bitbar"
    concurrency_method: eager

  - label: ":bitbar: :android: Run Android e2e tests for Unity 2022"
    timeout_in_minutes: 60
    depends_on: "build-android-fixture-2022"
    agents:
      queue: opensource
    env:
      UNITY_VERSION: *2022
    plugins:
      artifacts#v1.9.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2022.apk"
        upload:
          - "maze_output/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner-bitbar
        run: maze-runner-bitbar
        service-ports: true
        command:
          - "features/csharp"
          - "features/android"
          - "--app=features/fixtures/maze_runner/mazerunner_2022.apk"
          - "--farm=bb"
          - "--appium-version=1.22"
          - "--device=ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: "bitbar"
    concurrency_method: eager

  - label: ":bitbar: :android: Run Android e2e tests for Unity 2023"
    timeout_in_minutes: 60
    depends_on: "build-android-fixture-2023"
    agents:
      queue: opensource
    env:
      UNITY_VERSION: *2023
    plugins:
      artifacts#v1.9.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2023.apk"
        upload:
          - "maze_output/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner-bitbar
        run: maze-runner-bitbar
        service-ports: true
        command:
          - "features/csharp"
          - "features/android"
          - "--app=features/fixtures/maze_runner/mazerunner_2023.apk"
          - "--farm=bb"
          - "--appium-version=1.22"
          - "--device=ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: "bitbar"
    concurrency_method: eager

  # - label: ':android: Run Android EDM e2e tests for Unity 2020'
  #   timeout_in_minutes: 60
  #   depends_on: 'build-edm-fixture-2020'
  #   agents:
  #     queue: opensource
  #   env:
  #     UNITY_VERSION: *2021
  #   plugins:
  #     artifacts#v1.9.0:
  #       download:
  #         - "features/fixtures/EDM_Fixture/edm_2020.apk"
  #       upload:
  #         - "maze_output/**/*"
  #     docker-compose#v3.7.0:
  #       pull: maze-runner
  #       run: maze-runner
  #       command:
  #         - "--app=/app/features/fixtures/EDM_Fixture/edm_2020.apk"
  #         - "--farm=bs"
  #         - "--device=ANDROID_11_0"
  #         - "features/edm"
  #   concurrency: 5
  #   concurrency_group: browserstack-app
  #   concurrency_method: eager

