steps:

  #
  # Build notifier.  We run tests for all Unity versions with the 2017 artifacts, as that is what we ship.
  #
  - label: Build notifier artifacts
    key: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2017.4.40f1"
    commands:
      - bundle install
      - bundle exec rake plugin:export
    artifact_paths:
      - Bugsnag.unitypackage
      - Bugsnag-with-android-64bit.unitypackage

  #
  # Build MacOS and WebGL test fixtures
  #
  - label: Build Unity 2020 MacOS and WebGL test fixtures
    key: 'cocoa-webgl-2020-fixtures'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2020.3.23f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
    commands:
      - scripts/ci-build-macos-packages.sh
    artifact_paths:
      - unity.log
      - features/fixtures/maze_runner/build/MacOS-2020.3.23f1.zip
      - features/fixtures/maze_runner/build/WebGL-2020.3.23f1.zip
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 1
        - exit_status: 255 # Forced agent shutdown (e.g. timeout)
          limit: 1
  #
  # Run desktop tests
  #
  - label: Run MacOS e2e tests for Unity 2020
    depends_on: 'cocoa-webgl-2020-fixtures'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.23f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - features/fixtures/maze_runner/build/MacOS-2020.3.23f1.zip
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

  #
  # Run WebGL tests
  #
  - label: Run WebGL e2e tests for Unity 2020
    depends_on: 'cocoa-webgl-2020-fixtures'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.23f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - features/fixtures/maze_runner/build/WebGL-2020.3.23f1.zip
        upload:
          - maze_output/failed/**/*
    commands:
      - scripts/ci-run-webgl-tests.sh

  #
  # Build Android test fixtures
  #
  - label: ':android: Build Android test fixture for Unity 2020'
    key: 'build-android-fixture-2020'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2020.3.23f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2020.3.23f1.apk
          - features/fixtures/unity.log
    commands:
      - rake test:android:build
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 1
        - exit_status: 255 # Forced agent shutdown (e.g. timeout)
          limit: 1

  #
  # Run Android tests
  #
  - label: ':android: Run Android e2e tests for Unity 2020'
    depends_on: 'build-android-fixture-2020'
    timeout_in_minutes: 30
    agents:
      queue: opensource
    env:
      UNITY_VERSION: "2020.3.23f1"
    plugins:
      artifacts#v1.3.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2020.3.23f1.apk"
        upload:
          - "maze_output/failed/**/*"
      docker-compose#v3.3.0:
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2020.3.23f1.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "features/android"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager

  #
  # Build iOS test fixtures
  #
  - label: ':ios: Generate Xcode project - Unity 2020'
    key: 'generate-fixture-project-2020'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2020.3.23f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2020.3.23f1.ipa
          - features/fixtures/unity.log
          - project_2020.tgz
    commands:
      - rake test:ios:generate_xcode
      - tar -zvcf project_2020.tgz features/fixtures/maze_runner/mazerunner_xcode
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 1
        - exit_status: 255 # Forced agent shutdown (e.g. timeout)
          limit: 1

  - label: ':ios: Build iOS test fixture for Unity 2020'
    key: 'build-ios-fixture-2020'
    depends_on: 'generate-fixture-project-2020'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.23f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
          - project_2020.tgz
        upload:
          - features/fixtures/maze_runner/mazerunner_2020.3.23f1.ipa
          - features/fixtures/unity.log
    commands:
      - tar -zxf project_2020.tgz features/fixtures/maze_runner
      - rake test:ios:build_xcode
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 1
        - exit_status: 255 # Forced agent shutdown (e.g. timeout)
          limit: 1

  #
  # Run iOS tests
  #
  - label: ':ios: Run iOS e2e tests for Unity 2020'
    depends_on: 'build-ios-fixture-2020'
    timeout_in_minutes: 30
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2020.3.23f1.ipa"
        upload:
          - "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: maze-runner
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2020.3.23f1.ipa"
          - "--farm=bs"
          - "--device=IOS_14"
          - "--fail-fast"
          - "features/ios"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager

  #
  # Build Windows test fixture
  #
  - label: Build Unity 2020 Windows test fixture
    key: 'windows-2020-fixture'
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-windows-unity
    env:
      UNITY_VERSION: "2020.3.17f1"
    commands:
      - scripts/ci-build-windows-package.bat
    artifact_paths:
      - unity.log
      - features/fixtures/maze_runner/build/Windows-2020.3.17f1.zip
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 1
        - exit_status: 255 # Forced agent shutdown (e.g. timeout)
          limit: 1

  #
  # Run Windows e2e tests
  #
  - label: Run Windows e2e tests for Unity 2020
    depends_on: 'windows-2020-fixture'
    timeout_in_minutes: 30
    agents:
      queue: opensource-windows-unity
    env:
      UNITY_VERSION: "2020.3.17f1"
    command:
      - scripts/ci-run-windows-tests.bat
    artifact_paths:
      - maze_output/failed/**/*

  #
  # Conditionally trigger full pipeline
  #
  - label: 'Conditionally trigger full set of tests'
    command: sh -c .buildkite/pipeline_trigger.sh

