aliases:
  - &2021 "2021.3.36f1"

steps:
  - label: Build released notifier artifact
    key: "build_unitypackage"
    timeout_in_minutes: 30
    agents:
      queue: macos-14
    env:
      UNITY_VERSION: *2021
    commands:
      - bundle install
      - bundle exec rake plugin:export
    artifact_paths:
      - Bugsnag.unitypackage
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: Build Unity 2021 Windows test fixture
    timeout_in_minutes: 30
    key: "windows-2021-fixture"
    depends_on: "build_unitypackage"
    agents:
      queue: win-general-1
    env:
      UNITY_VERSION: *2021
    plugins:
      artifacts#v1.9.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - unity.log
          - features/fixtures/maze_runner/build/Windows-release-2021.zip
    commands:
      - scripts/ci-build-windows-fixture-wsl.sh release
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: Run Windows e2e tests for Unity 2021
    timeout_in_minutes: 30
    depends_on: "windows-2021-fixture"
    agents:
      queue: win-general-1
    env:
      UNITY_VERSION: *2021
    plugins:
      artifacts#v1.9.0:
        download:
          - features/fixtures/maze_runner/build/Windows-release-2021.zip
        upload:
          - maze_output/**/*
          - maze_output/metrics.csv
    command:
      - scripts/ci-run-windows-tests-wsl.sh release
