steps:
  # Run tests for all Unity versions with the 2017 artifacts, as that is what we ship
  - label: Build notifier artifacts
    key: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2017.4.40f1"
    commands:
      - bundle install
      - bundle exec rake plugin:export
    artifact_paths:
      - Bugsnag.unitypackage
      - Bugsnag-with-android-64bit.unitypackage
    concurrency: 2
    concurrency_group: 'unity-license'

  - label: Run e2e tests for Unity 2017.4.40f1
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2017.4.40f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
        upload:
          - test/desktop/maze_output/*
    commands:
      - cd test/desktop
      - bundle install
      - bundle exec bugsnag-maze-runner
    concurrency: 2
    concurrency_group: 'unity-license'

  - label: Run e2e tests for Unity 2018.4.34f1
    depends_on: 'build-artifacts'
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2018.4.34f1"
    plugins:
      artifacts#v1.2.0:
        download:
          - Bugsnag.unitypackage
          - Bugsnag-with-android-64bit.unitypackage
        upload:
          - test/desktop/maze_output/*
    commands:
      - cd test/desktop
      - bundle install
      - bundle exec bugsnag-maze-runner
    concurrency: 2
    concurrency_group: 'unity-license'
