aliases:
  - &2021 "2021.3.36f1"

steps:
  - group: ":hammer: Build Unity packages"
    steps:
      - label: Build released notifier artifact
        key: "build_unitypackage"
        timeout_in_minutes: 30
        agents:
          queue: macos-14
        env:
          UNITY_VERSION: *2021
        commands:
          - bundle install
          - bundle exec rake plugin:export
        artifact_paths:
          - Bugsnag.unitypackage
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: Ensure notifier builds on Windows (for development)
        timeout_in_minutes: 30
        agents:
          queue: windows-unity-wsl
        env:
          UNITY_VERSION: *2021
          WSLENV: UNITY_VERSION
        command:
          - /mnt/c/Windows/System32/cmd.exe /c  .\\scripts\\ci-build-windows-plugin.bat
        plugins:
          artifacts#v1.5.0:
            upload:
              - from: Bugsnag.unitypackage
                to: Bugsnag_WindowsBuilt.unitypackage
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

  - label: 'Run size impact reporting'
    depends_on: build_unitypackage
    timeout_in_minutes: 10
    env:
      UNITY_VERSION: *2021
    plugins:
      'artifacts#v1.9.0':
        download:
          - Bugsnag.unitypackage
    commands:
      features/scripts/do_size_test.sh

  - name: 'Append Unity 2021 Pipeline'
    depends_on: build_unitypackage
    commands:
        - buildkite-agent pipeline upload .buildkite/unity.2021.yml

  #
  # Conditionally trigger full pipeline
  #
  - label: "Conditionally trigger full set of tests"
    depends_on: build_unitypackage
    timeout_in_minutes: 30
    command: sh -c .buildkite/pipeline_trigger.sh
