aliases:
  - &2021 "2021.3.36f1"

agents:
  queue: macos-14

steps:
  - group: ":hammer: Build Unity 2021 test fixtures"
    steps:
      - label: ":android: Build Android test fixture for Unity 2021"
        timeout_in_minutes: 20
        key: "build-android-fixture-2021"
        env:
          UNITY_VERSION: *2021
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
            upload:
              - features/fixtures/maze_runner/mazerunner_2021.apk
              - features/fixtures/build_android_apk.log
        command:
              - "bundle install"
              - "features/build/build_android.feature"
              - "--os macos"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      #
      # Build iOS test fixtures
      #
      - label: ":ios: Generate Xcode project - Unity 2021"
        timeout_in_minutes: 20
        key: "generate-fixture-project-2021"
        env:
          UNITY_VERSION: *2021
        plugins:
          artifacts#v1.5.0:
            download:
              - Bugsnag.unitypackage
            upload:
              - features/fixtures/unity.log
              - project_2021.tgz
        commands:
          - bundle install
          - rake test:ios:generate_xcode
          - tar -zvcf project_2021.tgz features/fixtures/maze_runner/mazerunner_xcode
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":ios: Build iOS test fixture for Unity 2021"
        timeout_in_minutes: 10
        key: "build-ios-fixture-2021"
        depends_on: "generate-fixture-project-2021"
        env:
          UNITY_VERSION: *2021
          XCODE_VERSION: "15.3.0"
        plugins:
          artifacts#v1.5.0:
            download:
              - Bugsnag.unitypackage
              - project_2021.tgz
            upload:
              - features/fixtures/maze_runner/mazerunner_2021.ipa
              - features/fixtures/unity.log
        commands:
          - bundle install
          - tar -zxf project_2021.tgz features/fixtures/maze_runner
          - rake test:ios:build_xcode
        retry:
          automatic:
            - exit_status: "*"
              limit: 1


  - group: ":test_tube: E2E tests Unity 2021"
    steps:
      - label: ":bitbar: :android: Run Android e2e tests for Unity 2021"
        timeout_in_minutes: 60
        depends_on: "build-android-fixture-2021"
        agents:
          queue: opensource
        env:
          UNITY_VERSION: *2021
        plugins:
          artifacts#v1.5.0:
            download:
              - "features/fixtures/maze_runner/mazerunner_2021.apk"
            upload:
              - "maze_output/**/*"
              - "maze_output/metrics.csv"
          docker-compose#v4.7.0:
            pull: maze-runner-bitbar
            run: maze-runner-bitbar
            service-ports: true
            command:
              - "features/csharp"
              - "features/android"
              - "--app=features/fixtures/maze_runner/mazerunner_2021.apk"
              - "--farm=bb"
              - "--appium-version=1.22"
              - "--device=ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
              - "--no-tunnel"
              - "--aws-public-ip"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^master|next$$"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager

      - label: ":bitbar: :ios: Run iOS e2e tests for Unity 2021"
        timeout_in_minutes: 60
        depends_on: "build-ios-fixture-2021"
        agents:
          queue: opensource
        plugins:
          artifacts#v1.5.0:
            download:
              - "features/fixtures/maze_runner/mazerunner_2021.ipa"
            upload:
              - "maze_output/**/*"
              - "maze_output/metrics.csv"

          docker-compose#v4.7.0:
            pull: maze-runner-bitbar
            run: maze-runner-bitbar
            service-ports: true
            command:
              - "features/csharp"
              - "features/ios"
              - "--app=features/fixtures/maze_runner/mazerunner_2021.ipa"
              - "--farm=bb"
              - "--appium-version=1.22"
              - "--device=IOS_13|IOS_14|IOS_15"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "--fail-fast"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^master|next$$"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager