aliases:
  - &2022 "2022.3.62f1"

agents:
  queue: macos-15

steps:
  - group: ":hammer: Build Unity 2022 test fixtures"
    steps:
      - label: ":android: Build Android test fixture for Unity 2022"
        agents:
          queue: macos-15
        timeout_in_minutes: 30
        key: "build-android-fixture-2022"
        env:
          UNITY_VERSION: *2022
          JAVA_VERSION: 17
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
            upload:
              - features/fixtures/maze_runner/mazerunner_2022.apk
              - features/fixtures/build_android_apk.log
        command:
              - "bundle install"
              - "bundle exec maze-runner --os=macos --port=$((MAZE_RUNNER_PORT)) features/build/build_android.feature"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":ios: Build iOS test fixture for Unity 2022"
        timeout_in_minutes: 10
        key: "build-ios-fixture-2022"
        env:
          UNITY_VERSION: *2022
          XCODE_VERSION: "16.3.0"
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
            upload:
              - features/fixtures/maze_runner/mazerunner_2022.ipa
              - features/fixtures/unity.log
        command:
              - "bundle install"
              - "bundle exec maze-runner --os=macos --port=$((MAZE_RUNNER_PORT)) features/build/build_ios.feature"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: Build Unity 2022 MacOS fixture
        timeout_in_minutes: 10
        key: "macos-2022-fixture"
        env:
          UNITY_VERSION: *2022
          XCODE_VERSION: "16.3.0"
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
        commands:
          - scripts/ci-build-macos-fixture.sh release
        artifact_paths:
          - unity.log
          - features/fixtures/maze_runner/build/MacOS-release-2022.zip
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: Build Unity 2022 WebGL test fixture
        timeout_in_minutes: 10
        key: "webgl-2022-fixture"
        env:
          UNITY_VERSION: *2022
          XCODE_VERSION: "16.3.0"
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
        commands:
          - scripts/ci-build-webgl-fixture.sh release
        artifact_paths:
          - unity.log
          - features/fixtures/maze_runner/build/WebGL-release-2022.zip
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: Build Unity 2022 Windows test fixture
        timeout_in_minutes: 30
        key: "windows-2022-fixture"
        agents:
          queue: windows-general-wsl
        env:
          UNITY_VERSION: *2022
        commands:
          - scripts/ci-build-windows-fixture-wsl.sh release
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
            upload:
              - unity.log
              - unity_import.log
              - features/fixtures/maze_runner/build/Windows-release-2022.zip
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

  - group: ":test_tube: E2E tests Unity 2022"
    steps:
      - label: ":bitbar: :android: Run Android e2e tests for Unity 2022"
        timeout_in_minutes: 60
        depends_on: "build-android-fixture-2022"
        agents:
          queue: opensource
        env:
          UNITY_VERSION: *2022
        plugins:
          artifacts#v1.9.0:
            download:
              - "features/fixtures/maze_runner/mazerunner_2022.apk"
            upload:
              - "maze_output/**/*"
              - "maze_output/metrics.csv"
          docker-compose#v4.7.0:
            pull: maze-runner-bitbar
            run: maze-runner-bitbar
            service-ports: true
            command:
              - "features/csharp"
              - "features/android"
              - "--app=features/fixtures/maze_runner/mazerunner_2022.apk"
              - "--farm=bb"
              - "--appium-version=1.22"
              - "--device=ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "--fail-fast"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^master|next$$"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        retry:
          automatic:
            - exit_status: 103  # Appium session failed
              limit: 2

      - label: ":bitbar: :ios: Run iOS e2e tests for Unity 2022"
        timeout_in_minutes: 60
        depends_on: "build-ios-fixture-2022"
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.0:
            download:
              - "features/fixtures/maze_runner/mazerunner_2022.ipa"
            upload:
              - "maze_output/**/*"
              - "maze_output/metrics.csv"
          docker-compose#v4.7.0:
            pull: maze-runner-bitbar
            run: maze-runner-bitbar
            service-ports: true
            command:
              - "features/csharp"
              - "features/ios"
              - "--app=features/fixtures/maze_runner/mazerunner_2022.ipa"
              - "--farm=bb"
              - "--appium-version=1.22"
              - "--device=IOS_13|IOS_14|IOS_15"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "--fail-fast"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^master|next$$"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        retry:
          automatic:
            - exit_status: 103  # Appium session failed
              limit: 2

      - label: Run MacOS e2e tests for Unity 2022
        timeout_in_minutes: 60
        depends_on: 'macos-2022-fixture'
        agents:
          queue: macos-15-isolated
        env:
          UNITY_VERSION: *2022
        plugins:
          artifacts#v1.9.0:
            download:
              - features/fixtures/maze_runner/build/MacOS-release-2022.zip
            upload:
              - maze_output/**/*
              - '*-mazerunner.log'
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^master|next$$"
        commands:
          - scripts/ci-run-macos-tests.sh release

      - label: Run WebGL e2e tests for Unity 2022
        timeout_in_minutes: 30
        depends_on: 'webgl-2022-fixture'
        agents:
          queue: macos-15-isolated
        env:
          UNITY_VERSION: *2022
        plugins:
          artifacts#v1.9.0:
            download:
              - features/fixtures/maze_runner/build/WebGL-release-2022.zip
            upload:
              - maze_output/**/*
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^master|next$$"
        # TODO: WebGL persistence tests are currently skipped pending PLAT-8151
        commands:
          - scripts/ci-run-webgl-tests.sh release

      - label: Run Windows e2e tests for Unity 2022
        timeout_in_minutes: 30
        depends_on: "windows-2022-fixture"
        agents:
          queue: windows-general-isolated
        env:
          UNITY_VERSION: *2022
        plugins:
          artifacts#v1.9.0:
            download:
              - features/fixtures/maze_runner/build/Windows-release-2022.zip
            upload:
              - maze_output/**/*
              - maze_output/metrics.csv
        commands:
          - scripts/ci-run-windows-tests-wsl.sh release
