aliases:
  - &6000 "6000.0.36f1"

agents:
  queue: macos-14

steps:
  - group: ":hammer: Build Unity 6000 test fixtures"
    steps:
      - label: ":android: Build Android test fixture for Unity 6000"
        timeout_in_minutes: 20
        key: "build-android-fixture-6000"
        env:
          UNITY_VERSION: *6000
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
            upload:
              - features/fixtures/maze_runner/mazerunner_6000.apk
              - features/fixtures/build_android_apk.log
        command:
              - "bundle install"
              - "bundle exec maze-runner --os macos features/build/build_android.feature"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":ios: Build iOS test fixture for Unity 6000"
        timeout_in_minutes: 10
        key: "build-ios-fixture-6000"
        env:
          UNITY_VERSION: *6000
          XCODE_VERSION: "16.0.0"
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
            upload:
              - features/fixtures/maze_runner/mazerunner_6000.ipa
              - features/fixtures/unity.log
        command:
              - "bundle install"
              - "bundle exec maze-runner --os macos features/build/build_ios.feature"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: Build Unity 6000 MacOS test fixture
        timeout_in_minutes: 10
        key: "macos-6000-fixture"
        env:
          UNITY_VERSION: *6000
          XCODE_VERSION: "16.0.0"
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
        commands:
          - scripts/ci-build-macos-fixture.sh release
        artifact_paths:
          - unity.log
          - features/fixtures/maze_runner/build/MacOS-release-6000.zip
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: Build Unity 6000 WebGL test fixture
        timeout_in_minutes: 10
        key: "webgl-6000-fixture"
        env:
          UNITY_VERSION: *6000
          XCODE_VERSION: "16.0.0"
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
        commands:
          - scripts/ci-build-webgl-fixture.sh release
        artifact_paths:
          - unity.log
          - features/fixtures/maze_runner/build/WebGL-release-6000.zip
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: Build Unity 6000 Windows test fixture
        skip: Pending PLAT-12072
        timeout_in_minutes: 30
        key: "windows-6000-fixture"
        agents:
          queue: windows-unity-wsl
        env:
          UNITY_VERSION: *6000
        commands:
          - scripts/ci-build-windows-fixture-wsl.sh release
        plugins:
          artifacts#v1.9.0:
            download:
              - Bugsnag.unitypackage
            upload:
              - unity.log
              - unity_import.log
              - features/fixtures/maze_runner/build/Windows-release-6000.zip
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

  - group: ":test_tube: E2E tests Unity 6000"
    steps:
      - label: ":bitbar: :android: Run Android e2e tests for Unity 6000"
        timeout_in_minutes: 60
        depends_on: "build-android-fixture-6000"
        agents:
          queue: opensource
        env:
          UNITY_VERSION: *6000
        plugins:
          artifacts#v1.9.0:
            download:
              - "features/fixtures/maze_runner/mazerunner_6000.apk"
            upload:
              - "maze_output/**/*"
              - "maze_output/metrics.csv"
          docker-compose#v4.7.0:
            pull: maze-runner-bitbar
            run: maze-runner-bitbar
            service-ports: true
            command:
              - "features/csharp"
              - "features/android"
              - "--app=features/fixtures/maze_runner/mazerunner_6000.apk"
              - "--farm=bb"
              - "--appium-version=1.22"
              - "--device=ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "--fail-fast"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^master|next$$"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager

      - label: ":bitbar: :ios: Run iOS e2e tests for Unity 6000"
        timeout_in_minutes: 60
        depends_on: "build-ios-fixture-6000"
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.0:
            download:
              - "features/fixtures/maze_runner/mazerunner_6000.ipa"
            upload:
              - "maze_output/**/*"
              - "maze_output/metrics.csv"
          docker-compose#v4.7.0:
            pull: maze-runner-bitbar
            run: maze-runner-bitbar
            service-ports: true
            command:
              - "features/csharp"
              - "features/ios"
              - "--app=features/fixtures/maze_runner/mazerunner_6000.ipa"
              - "--farm=bb"
              - "--appium-version=1.22"
              - "--device=IOS_13|IOS_14|IOS_15"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "--fail-fast"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^master|next$$"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager

      - label: Run MacOS e2e tests for Unity 6000
        timeout_in_minutes: 60
        depends_on: 'macos-6000-fixture'
        agents:
          queue: macos-14
        env:
          UNITY_VERSION: *6000
        plugins:
          artifacts#v1.9.0:
            download:
              - features/fixtures/maze_runner/build/MacOS-release-6000.zip
            upload:
              - maze_output/**/*
              - '*-mazerunner.log'
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^master|next$$"
        commands:
          - scripts/ci-run-macos-tests.sh release

      - label: Run WebGL e2e tests for Unity 6000
        timeout_in_minutes: 30
        depends_on: 'webgl-6000-fixture'
        env:
          UNITY_VERSION: *6000
        plugins:
          artifacts#v1.9.0:
            download:
              - features/fixtures/maze_runner/build/WebGL-release-6000.zip
            upload:
              - maze_output/**/*
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^master|next$$"
        # TODO: WebGL persistence tests are currently skipped pending PLAT-8151
        commands:
          - scripts/ci-run-webgl-tests.sh release

      - label: Run Windows e2e tests for Unity 6000
        skip: Pending PLAT-12072
        timeout_in_minutes: 30
        depends_on: "windows-6000-fixture"
        agents:
          queue: windows-general-wsl
        env:
          UNITY_VERSION: *6000
        plugins:
          artifacts#v1.9.0:
            download:
              - features/fixtures/maze_runner/build/Windows-release-6000.zip
            upload:
              - maze_output/**/*
              - maze_output/metrics.csv
        commands:
          - scripts/ci-run-windows-tests-wsl.sh release
