name: update-dependencies

on:
  push:
    branches:
      - 'dep-updater'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    env:
      TARGET_SUBMODULE: bugsnag-cocoa
      TARGET_VERSION: v6.0.1
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dep-updater

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - run: bundle exec rake dependencies:update

      - name: Create pull request
        if: ${{ github.ref != 'refs/heads/dep-updater'}}
        run: gh pr create -B next |
         -H bumpsnag-${{ github.event.client_payload.target_submodule }}-${{ github.event.client_payload.target_version }} |
         --title 'Update ${{github.event.client_payload.target_submodule }} to version ${{ github.event.client_payload.target_version }}' |
         --body 'Created by bumpsnag' |
         --reviewer cawllec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

