name: update-dependencies

on:
  push:
    branches:
      - 'dep-updater'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    env:
      TARGET_SUBMODULE: bugsnag-cocoa
      TARGET_VERSION: v6.1.0
      BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_ACCESS_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dep-updater

      - run: |
          git config --global user.name 'Bumpsnag bot'
          git config --global user.email ''

      - run: git fetch --prune --unshallow

      - run: git submodule update --init --recursive

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - run: bundle exec rake dependencies:update

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Create pull request
        if: ${{ github.ref != 'refs/heads/dep-updater'}}
        run: gh pr create -B dep-updater |
         -H bumpsnag-$TARGET_SUBMODULE-$TARGET_VERSION |
         --title 'Update $TARGET_SUBMODULE to version $TARGET_VERSION' |
         --body 'Created by bumpsnag' |
         --reviewer cawllec
